theme: jekyll-theme-slate
title: Welcome to Alex Tran's Github Pages!
description: This page serves as my portfolio and project showcase. Feel free to take a closer look at any of the projects below!
